### ISSUE TITLE
Error: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by johnvanham** [tflanagan/node-qb-record#20]
Hello @tflanagan 

I'm trying to use this in a react web app which is built with Webpack.

I can use the quickbase library fine but when trying to use your abstraction layer for records I'm getting this error from webpack:

`ERROR in ./node_modules/rfc4122/rfc4122.js 19:15-32
Module not found: Error: Can't resolve 'crypto'`

`BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.`

Is there an easy way to resolve this? I had the same issue with qb-table as well.

**Comment by tflanagan** [comment]
@johnvanham Looks like this is an issue with webpack, not with this library.

From a quick google search, looks like someone has solved this problem: https://github.com/Richienb/node-polyfill-webpack-plugin

**Comment by johnvanham** [comment]
@tflanagan 

Thanks, I have solved this a slightly different way.. in case this helps others, since I don't think I will be the only person wanting to use your library with webpack..

I installed `crypto-browserify` and `stream-browserify`.

Then in `webpack.config.js` added:

```
resolve: {
    fallback: {
        "crypto": require.resolve("crypto-browserify"),
        "stream": require.resolve("stream-browserify"),
    }
}
```
